[mypy]
python_version = 3.11
ignore_missing_imports = True
check_untyped_defs = True
disable_error_code = import-untyped, name-defined

# Specific to Platform logic
[mypy-typer.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-projectdavid.*]
ignore_missing_imports = True
